name: social-network

networks:
  social-network-net:
    driver: bridge

volumes:
  user-data:
  posts-data:

services:
  user-postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "users-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - social-network-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  posts-postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "posts-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - posts-data:/var/lib/postgresql/data
    networks:
      - social-network-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - social-network-net
    depends_on:
      - posts-service

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - social-network-net
    depends_on:
      user-postgres:
        condition: service_healthy

  posts-service:
    build:
      context: .
      dockerfile: ./posts-comments-service/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - social-network-net
    depends_on:
      posts-postgres:
        condition: service_healthy
