// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: posts.proto

package posts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostsService_AddPost_FullMethodName                 = "/PostsService/AddPost"
	PostsService_DeletePost_FullMethodName              = "/PostsService/DeletePost"
	PostsService_GetPostById_FullMethodName             = "/PostsService/GetPostById"
	PostsService_UpdatePost_FullMethodName              = "/PostsService/UpdatePost"
	PostsService_GetAllPostsPaginated_FullMethodName    = "/PostsService/GetAllPostsPaginated"
	PostsService_LikeEvent_FullMethodName               = "/PostsService/LikeEvent"
	PostsService_AddComment_FullMethodName              = "/PostsService/AddComment"
	PostsService_ViewEvent_FullMethodName               = "/PostsService/ViewEvent"
	PostsService_GetAllCommentsPaginated_FullMethodName = "/PostsService/GetAllCommentsPaginated"
)

// PostsServiceClient is the client API for PostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostsServiceClient interface {
	AddPost(ctx context.Context, in *PostEssential, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeletePost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPostById(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*Post, error)
	UpdatePost(ctx context.Context, in *PostWithNoUser, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAllPostsPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*AllPosts, error)
	LikeEvent(ctx context.Context, in *Like, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ViewEvent(ctx context.Context, in *View, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAllCommentsPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*AllComments, error)
}

type postsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostsServiceClient(cc grpc.ClientConnInterface) PostsServiceClient {
	return &postsServiceClient{cc}
}

func (c *postsServiceClient) AddPost(ctx context.Context, in *PostEssential, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PostsService_AddPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) DeletePost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PostsService_DeletePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPostById(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*Post, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Post)
	err := c.cc.Invoke(ctx, PostsService_GetPostById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) UpdatePost(ctx context.Context, in *PostWithNoUser, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PostsService_UpdatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetAllPostsPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*AllPosts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllPosts)
	err := c.cc.Invoke(ctx, PostsService_GetAllPostsPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) LikeEvent(ctx context.Context, in *Like, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PostsService_LikeEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) AddComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PostsService_AddComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) ViewEvent(ctx context.Context, in *View, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PostsService_ViewEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetAllCommentsPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*AllComments, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllComments)
	err := c.cc.Invoke(ctx, PostsService_GetAllCommentsPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServiceServer is the server API for PostsService service.
// All implementations must embed UnimplementedPostsServiceServer
// for forward compatibility.
type PostsServiceServer interface {
	AddPost(context.Context, *PostEssential) (*emptypb.Empty, error)
	DeletePost(context.Context, *PostId) (*emptypb.Empty, error)
	GetPostById(context.Context, *PostId) (*Post, error)
	UpdatePost(context.Context, *PostWithNoUser) (*emptypb.Empty, error)
	GetAllPostsPaginated(context.Context, *Pagination) (*AllPosts, error)
	LikeEvent(context.Context, *Like) (*emptypb.Empty, error)
	AddComment(context.Context, *Comment) (*emptypb.Empty, error)
	ViewEvent(context.Context, *View) (*emptypb.Empty, error)
	GetAllCommentsPaginated(context.Context, *Pagination) (*AllComments, error)
	mustEmbedUnimplementedPostsServiceServer()
}

// UnimplementedPostsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostsServiceServer struct{}

func (UnimplementedPostsServiceServer) AddPost(context.Context, *PostEssential) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPost not implemented")
}
func (UnimplementedPostsServiceServer) DeletePost(context.Context, *PostId) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedPostsServiceServer) GetPostById(context.Context, *PostId) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostById not implemented")
}
func (UnimplementedPostsServiceServer) UpdatePost(context.Context, *PostWithNoUser) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedPostsServiceServer) GetAllPostsPaginated(context.Context, *Pagination) (*AllPosts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPostsPaginated not implemented")
}
func (UnimplementedPostsServiceServer) LikeEvent(context.Context, *Like) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeEvent not implemented")
}
func (UnimplementedPostsServiceServer) AddComment(context.Context, *Comment) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedPostsServiceServer) ViewEvent(context.Context, *View) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewEvent not implemented")
}
func (UnimplementedPostsServiceServer) GetAllCommentsPaginated(context.Context, *Pagination) (*AllComments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCommentsPaginated not implemented")
}
func (UnimplementedPostsServiceServer) mustEmbedUnimplementedPostsServiceServer() {}
func (UnimplementedPostsServiceServer) testEmbeddedByValue()                      {}

// UnsafePostsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostsServiceServer will
// result in compilation errors.
type UnsafePostsServiceServer interface {
	mustEmbedUnimplementedPostsServiceServer()
}

func RegisterPostsServiceServer(s grpc.ServiceRegistrar, srv PostsServiceServer) {
	// If the following call pancis, it indicates UnimplementedPostsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostsService_ServiceDesc, srv)
}

func _PostsService_AddPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostEssential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).AddPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_AddPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).AddPost(ctx, req.(*PostEssential))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).DeletePost(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPostById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPostById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPostById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPostById(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostWithNoUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).UpdatePost(ctx, req.(*PostWithNoUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetAllPostsPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetAllPostsPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetAllPostsPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetAllPostsPaginated(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_LikeEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Like)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).LikeEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_LikeEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).LikeEvent(ctx, req.(*Like))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_AddComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).AddComment(ctx, req.(*Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_ViewEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(View)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).ViewEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_ViewEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).ViewEvent(ctx, req.(*View))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetAllCommentsPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetAllCommentsPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetAllCommentsPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetAllCommentsPaginated(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

// PostsService_ServiceDesc is the grpc.ServiceDesc for PostsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PostsService",
	HandlerType: (*PostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPost",
			Handler:    _PostsService_AddPost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostsService_DeletePost_Handler,
		},
		{
			MethodName: "GetPostById",
			Handler:    _PostsService_GetPostById_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostsService_UpdatePost_Handler,
		},
		{
			MethodName: "GetAllPostsPaginated",
			Handler:    _PostsService_GetAllPostsPaginated_Handler,
		},
		{
			MethodName: "LikeEvent",
			Handler:    _PostsService_LikeEvent_Handler,
		},
		{
			MethodName: "AddComment",
			Handler:    _PostsService_AddComment_Handler,
		},
		{
			MethodName: "ViewEvent",
			Handler:    _PostsService_ViewEvent_Handler,
		},
		{
			MethodName: "GetAllCommentsPaginated",
			Handler:    _PostsService_GetAllCommentsPaginated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "posts.proto",
}

const (
	StatisticsService_GetLikesViewsComments_FullMethodName = "/StatisticsService/GetLikesViewsComments"
	StatisticsService_GetViewsDynamic_FullMethodName       = "/StatisticsService/GetViewsDynamic"
	StatisticsService_GetLikesDynamic_FullMethodName       = "/StatisticsService/GetLikesDynamic"
	StatisticsService_GetCommentsDynamic_FullMethodName    = "/StatisticsService/GetCommentsDynamic"
	StatisticsService_GetPostsTop_FullMethodName           = "/StatisticsService/GetPostsTop"
	StatisticsService_GetUsersTop_FullMethodName           = "/StatisticsService/GetUsersTop"
)

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	GetLikesViewsComments(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*LikesViewsComments, error)
	GetViewsDynamic(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*ViewsDynamicArr, error)
	GetLikesDynamic(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*LikesDynamicArr, error)
	GetCommentsDynamic(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*CommentsDynamicArr, error)
	GetPostsTop(ctx context.Context, in *Type, opts ...grpc.CallOption) (*PostsTop, error)
	GetUsersTop(ctx context.Context, in *Type, opts ...grpc.CallOption) (*UsersTop, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) GetLikesViewsComments(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*LikesViewsComments, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikesViewsComments)
	err := c.cc.Invoke(ctx, StatisticsService_GetLikesViewsComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetViewsDynamic(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*ViewsDynamicArr, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewsDynamicArr)
	err := c.cc.Invoke(ctx, StatisticsService_GetViewsDynamic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetLikesDynamic(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*LikesDynamicArr, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikesDynamicArr)
	err := c.cc.Invoke(ctx, StatisticsService_GetLikesDynamic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetCommentsDynamic(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*CommentsDynamicArr, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentsDynamicArr)
	err := c.cc.Invoke(ctx, StatisticsService_GetCommentsDynamic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetPostsTop(ctx context.Context, in *Type, opts ...grpc.CallOption) (*PostsTop, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostsTop)
	err := c.cc.Invoke(ctx, StatisticsService_GetPostsTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetUsersTop(ctx context.Context, in *Type, opts ...grpc.CallOption) (*UsersTop, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersTop)
	err := c.cc.Invoke(ctx, StatisticsService_GetUsersTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility.
type StatisticsServiceServer interface {
	GetLikesViewsComments(context.Context, *PostId) (*LikesViewsComments, error)
	GetViewsDynamic(context.Context, *PostId) (*ViewsDynamicArr, error)
	GetLikesDynamic(context.Context, *PostId) (*LikesDynamicArr, error)
	GetCommentsDynamic(context.Context, *PostId) (*CommentsDynamicArr, error)
	GetPostsTop(context.Context, *Type) (*PostsTop, error)
	GetUsersTop(context.Context, *Type) (*UsersTop, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatisticsServiceServer struct{}

func (UnimplementedStatisticsServiceServer) GetLikesViewsComments(context.Context, *PostId) (*LikesViewsComments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikesViewsComments not implemented")
}
func (UnimplementedStatisticsServiceServer) GetViewsDynamic(context.Context, *PostId) (*ViewsDynamicArr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetViewsDynamic not implemented")
}
func (UnimplementedStatisticsServiceServer) GetLikesDynamic(context.Context, *PostId) (*LikesDynamicArr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikesDynamic not implemented")
}
func (UnimplementedStatisticsServiceServer) GetCommentsDynamic(context.Context, *PostId) (*CommentsDynamicArr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsDynamic not implemented")
}
func (UnimplementedStatisticsServiceServer) GetPostsTop(context.Context, *Type) (*PostsTop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostsTop not implemented")
}
func (UnimplementedStatisticsServiceServer) GetUsersTop(context.Context, *Type) (*UsersTop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersTop not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}
func (UnimplementedStatisticsServiceServer) testEmbeddedByValue()                           {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatisticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_GetLikesViewsComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetLikesViewsComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetLikesViewsComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetLikesViewsComments(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetViewsDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetViewsDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetViewsDynamic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetViewsDynamic(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetLikesDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetLikesDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetLikesDynamic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetLikesDynamic(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetCommentsDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetCommentsDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetCommentsDynamic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetCommentsDynamic(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetPostsTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Type)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPostsTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPostsTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPostsTop(ctx, req.(*Type))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetUsersTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Type)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetUsersTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetUsersTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetUsersTop(ctx, req.(*Type))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLikesViewsComments",
			Handler:    _StatisticsService_GetLikesViewsComments_Handler,
		},
		{
			MethodName: "GetViewsDynamic",
			Handler:    _StatisticsService_GetViewsDynamic_Handler,
		},
		{
			MethodName: "GetLikesDynamic",
			Handler:    _StatisticsService_GetLikesDynamic_Handler,
		},
		{
			MethodName: "GetCommentsDynamic",
			Handler:    _StatisticsService_GetCommentsDynamic_Handler,
		},
		{
			MethodName: "GetPostsTop",
			Handler:    _StatisticsService_GetPostsTop_Handler,
		},
		{
			MethodName: "GetUsersTop",
			Handler:    _StatisticsService_GetUsersTop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "posts.proto",
}
